# Generated by Django 4.1 on 2023-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
