# Generated by Django 4.1 on 2023-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_created_by_customuser_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
