# Generated by Django 4.1 on 2023-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_date',
            field=models.DateField(null=True),
        ),
    ]
