# Generated by Django 4.1 on 2023-06-13 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_approved_by_customuser_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
