# Generated by Django 4.1 on 2023-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_registration_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_type',
            field=models.CharField(choices=[('m', 'Anugyapatra Qc Department'), ('su', 'surveillance Food Inspectors'), ('f', 'kathmandu'), ('fk', 'ktm'), ('fdh', 'dhulikhel'), ('fsur', 'surkhet'), ('ftha', 'tanahun'), ('fp', 'pokhara'), ('fex', 'other'), ('fnu', 'nuwakot'), ('fsin', 'sindhuli')], default=None, max_length=60),
        ),
    ]
