# Generated by Django 4.1 on 2023-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_department_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_address',
            field=models.CharField(choices=[('f', 'kathmandu'), ('fk', 'ktm'), ('fdh', 'dhulikhel'), ('fsur', 'surkhet'), ('ftha', 'tanahun'), ('fp', 'pokhara'), ('fex', 'other'), ('fnu', 'nuwakot'), ('fsin', 'sindhuli')], default=None, max_length=60),
        ),
    ]
