# Generated by Django 4.1 on 2023-06-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_customuser_department_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department_address',
            new_name='department_type',
        ),
    ]
