# Generated by Django 4.1 on 2023-06-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_customuser_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
