# Generated by Django 4.1 on 2023-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customuser_department_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_address',
            field=models.CharField(choices=[('f', 'Kathmandu'), ('fk', 'Ktm'), ('fdh', 'Dhulikhel'), ('fsur', 'Surkhet'), ('ftha', 'Tanahun'), ('fp', 'Pokhara'), ('fex', 'Other'), ('fnu', 'Nuwakot'), ('fsin', 'Sindhuli')], default=None, max_length=60),
        ),
    ]
