# Generated by Django 4.1 on 2023-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_customuser_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chemical', 'Chemical'), ('Instrumental', 'Instrumental'), ('Microbiological', 'Microbiological')], default=None, max_length=155, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='test_type',
            field=models.ManyToManyField(default=None, null=True, related_name='users', to='account.testtype'),
        ),
    ]
