# Generated by Django 4.1 on 2023-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_testtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_types',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
