# Generated by Django 4.1 on 2023-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
