# Generated by Django 4.1 on 2023-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_customuser_is_recheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_document', models.FileField(default=None, upload_to='media/user/customuserimages')),
            ],
        ),
    ]
