# Generated by Django 4.1 on 2023-07-26 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_customuserimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserimages',
            old_name='registration_document',
            new_name='file',
        ),
        migrations.AddField(
            model_name='customuserimages',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuserimages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
