# Generated by Django 4.1 on 2023-08-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_customuser_importer_address_customuser_importer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_address',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
