# Generated by Django 4.1 on 2023-05-18 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('test_duration', models.IntegerField(null=True)),
                ('units', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user', models.EmailField(default=None, max_length=100)),
                ('name', models.CharField(max_length=255, null=True)),
                ('condition', models.CharField(max_length=255)),
                ('mfd', models.DateField()),
                ('dfb', models.DateField()),
                ('batch', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('report_date', models.DateField()),
                ('amendments', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('note', models.TextField()),
                ('commodity_id', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('processing', 'processing'), ('completed', 'completed'), ('reject', 'reject')], max_length=155, null=True)),
                ('form_available', models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SampleFormParameterFormulaCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=255, null=True)),
                ('formula_notation', models.TextField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=255, null=True)),
                ('ref_test_method', models.CharField(max_length=255, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('results', models.CharField(max_length=100, null=True)),
                ('mandatory_standard', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(max_length=500, null=True)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='management.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFormHasParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_user', models.EmailField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('processing', 'processing'), ('completed', 'completed'), ('reject', 'reject')], max_length=155, null=True)),
                ('form_available', models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_has_parameter_analyst', to='management.commodity')),
                ('parameter', models.ManyToManyField(related_name='sample_has_parameters', to='management.testresult')),
                ('sample_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_has_parameter_analyst', to='management.sampleform')),
            ],
        ),
        migrations.AddField(
            model_name='sampleform',
            name='parameters',
            field=models.ManyToManyField(related_name='sample_form', to='management.testresult'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=100, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=155, null=True)),
                ('register_date', models.CharField(blank=True, max_length=155, null=True)),
                ('ammount', models.IntegerField(blank=True, null=True)),
                ('payment_receipt', models.FileField(null=True, upload_to='uploads/receipt')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_form', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='management.sampleform')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='management.commoditycategory'),
        ),
    ]
