# Generated by Django 4.1 on 2023-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformparameterformulacalculate',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
