# Generated by Django 4.1 on 2023-05-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_sampleform_supervisor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='supervisor_user',
        ),
        migrations.AddField(
            model_name='sampleform',
            name='supervisor_user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_has_parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
