# Generated by Django 4.1 on 2023-05-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_sampleform_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='supervisor_user',
        ),
    ]
