# Generated by Django 4.1 on 2023-05-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_sampleformhasparameter_analyst_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='commodity_id',
        ),
        migrations.AddField(
            model_name='sampleform',
            name='commodity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.commodity'),
        ),
    ]
