# Generated by Django 4.1 on 2023-05-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_sampleform_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='commodity',
        ),
    ]
