# Generated by Django 4.1 on 2023-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_sampleform_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='commodity_id',
            field=models.IntegerField(null=True),
        ),
    ]
