# Generated by Django 4.1 on 2023-05-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_sampleform_commodity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleform',
            name='commodity_id',
        ),
    ]
