# Generated by Django 4.1 on 2023-05-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_sampleform_commodity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleform',
            old_name='commodity_id',
            new_name='commodity',
        ),
    ]
