# Generated by Django 4.1 on 2023-06-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_sampleform_is_commodity_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='sample_form', to='management.testresult'),
        ),
        migrations.CreateModel(
            name='SampleFormVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sample_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='management.sampleform')),
            ],
        ),
    ]
