# Generated by Django 4.1 on 2023-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_sampleformverifier_sample_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='form_available',
            field=models.CharField(blank=True, choices=[('superadmin', 'superadmin'), ('smu', 'smu'), ('supervisor', 'supervisor'), ('analyst', 'analyst'), ('user', 'user'), ('verifier', 'verifier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('processing', 'processing'), ('not_verified', 'not_verified'), ('completed', 'completed'), ('rejected', 'rejected')], max_length=155, null=True),
        ),
    ]
