# Generated by Django 4.1 on 2023-06-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_sampleformhasparameter_is_tested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleformhasparameter',
            old_name='is_tested',
            new_name='is_supervisor_sent',
        ),
    ]
