# Generated by Django 4.1 on 2023-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_sampleform_is_analyst_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformparameterformulacalculate',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('completed', 'completed')], max_length=155, null=True),
        ),
    ]
