# Generated by Django 4.1 on 2023-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_sampleformparameterformulacalculate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('completed', 'completed')], default='completed', max_length=155),
        ),
    ]
