# Generated by Django 4.1 on 2023-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_sampleformparameterformulacalculate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='amendments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('not_assigned', 'not_assigned'), ('not_verified', 'not_verified'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected')], max_length=155, null=True),
        ),
    ]
