# Generated by Django 4.1 on 2023-06-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_sampleformhasparameter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
