# Generated by Django 4.1 on 2023-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_sampleform_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='amendments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
