# Generated by Django 4.1 on 2023-06-16 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_sampleform_amendments_alter_sampleform_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformverifier',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sampleformverifier',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
