# Generated by Django 4.1 on 2023-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_rename_ammount_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='remarks',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
