# Generated by Django 4.1 on 2023-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_alter_sampleform_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='requested_export',
            field=models.CharField(choices=[('r', 'request'), ('e', 'export')], default=None, max_length=155),
        ),
    ]
