# Generated by Django 4.1 on 2023-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_sampleform_analyst_encode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='requested_export',
            field=models.CharField(choices=[('r', 'request'), ('e', 'export')], default=None, max_length=155, null=True),
        ),
    ]
