# Generated by Django 4.1 on 2023-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_alter_sampleform_requested_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
