# Generated by Django 4.1 on 2023-06-23 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_rawdatasheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdatasheet',
            name='sample_form',
        ),
        migrations.RemoveField(
            model_name='rawdatasheet',
            name='sample_form_has_parameter',
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='auto_calculate_result',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='input_fields_value',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.testresult'),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='result',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
