# Generated by Django 4.1 on 2023-06-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_remove_rawdatasheet_auto_calculate_result_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rawDataSheet',
        ),
    ]
