# Generated by Django 4.1 on 2023-06-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_delete_rawdatasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raw_datasheet', to='management.sampleform')),
                ('sample_form_has_parameter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raw_datasheet', to='management.sampleformhasparameter')),
            ],
        ),
        migrations.CreateModel(
            name='RawDataSheetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('input_fields_value', models.CharField(max_length=2000, null=True)),
                ('auto_calculate_result', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.testresult')),
                ('raw_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='management.rawdatasheet')),
            ],
        ),
    ]
