# Generated by Django 4.1 on 2023-06-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_rawdatasheet_rawdatasheetdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformparameterformulacalculate',
            name='sample_form_has_parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='formula_calculate', to='management.sampleformhasparameter'),
        ),
    ]
