# Generated by Django 4.1 on 2023-06-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_sampleformparameterformulacalculate_sample_form_has_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleformparameterformulacalculate',
            old_name='remark',
            new_name='remarks',
        ),
    ]
