# Generated by Django 4.1 on 2023-06-25 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_rename_remark_sampleformparameterformulacalculate_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='status',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
