# Generated by Django 4.1 on 2023-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_rawdatasheet_analyst_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('not_assigned', 'not_assigned'), ('not_verified', 'not_verified'), ('verified', 'verified'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('recheck', 'recheck'), ('reject', 'reject'), ('not_verified', 'not_verified'), ('verified', 'verified')], default='pending', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('recheck', 'recheck'), ('completed', 'completed'), ('processing', 'processing')], default='processing', max_length=155),
        ),
    ]
