# Generated by Django 4.1 on 2023-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_rawdatasheet_analyst_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('not_verified', 'not_verified')], default='pending', max_length=155, null=True),
        ),
    ]
