# Generated by Django 4.1 on 2023-06-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_alter_sampleform_status_and_more'),
        ('management', '0064_alter_sampleformhasparameter_status'),
    ]

    operations = [
    ]
