# Generated by Django 4.1 on 2023-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_rawdatasheet_supervisor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditycategory',
            name='name_nepali',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
