# Generated by Django 4.1 on 2023-06-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_merge_20230626_0557'),
        ('management', '0065_rawdatasheet_supervisor_remarks'),
    ]

    operations = [
    ]
