# Generated by Django 4.1 on 2023-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_commoditycategory_name_nepali'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='name_nepali',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
