# Generated by Django 4.1 on 2023-06-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_merge_20230626_1103'),
        ('management', '0067_commodity_name_nepali'),
    ]

    operations = [
    ]
