# Generated by Django 4.1 on 2023-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_commodity_name_nepali'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='remarks_recheck_verifier',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='remarks_reject_verifier',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
