# Generated by Django 4.1 on 2023-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_sampleform_remarks_recheck_verifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='mandatory_standard_nepali',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='name_nepali',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_type_nepali',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='units_nepali',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('Biochemical', 'Biochemical'), ('Instrumental', 'Instrumental'), ('Microbiological', 'Microbiological')], default=None, max_length=155, null=True),
        ),
    ]
