# Generated by Django 4.1 on 2023-06-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_merge_20230627_0847'),
        ('management', '0068_sampleform_remarks_recheck_verifier_and_more'),
    ]

    operations = [
    ]
