# Generated by Django 4.1 on 2023-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_testresult_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='notation',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
