# Generated by Django 4.1 on 2023-06-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_alter_testresult_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='notation',
        ),
    ]
