# Generated by Django 4.1 on 2023-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_merge_20230627_1127'),
        ('management', '0071_alter_testresult_notation'),
    ]

    operations = [
    ]
