# Generated by Django 4.1 on 2023-06-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_merge_20230627_1346'),
        ('management', '0073_alter_commodity_test_duration'),
    ]

    operations = [
    ]
