# Generated by Django 4.1 on 2023-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_alter_payment_sample_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='requested_export',
            field=models.CharField(default=None, max_length=155, null=True),
        ),
    ]
