# Generated by Django 4.1 on 2023-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_alter_payment_sample_form_and_more'),
        ('management', '0074_merge_20230627_1547'),
    ]

    operations = [
    ]
