# Generated by Django 4.1 on 2023-06-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0075_alter_sampleform_requested_export'),
        ('management', '0075_merge_20230628_1154'),
    ]

    operations = [
    ]
