# Generated by Django 4.1 on 2023-06-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_alter_sampleform_requested_export'),
        ('management', '0076_merge_20230628_1233'),
    ]

    operations = [
    ]
