# Generated by Django 4.1 on 2023-06-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_supervisorsampleform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorsampleform',
            old_name='parameter',
            new_name='parameters',
        ),
    ]
