# Generated by Django 4.1 on 2023-06-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_merge_20230628_1636'),
        ('management', '0077_supervisorsampleform'),
    ]

    operations = [
    ]
