# Generated by Django 4.1 on 2023-06-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_merge_20230630_1145'),
        ('management', '0079_supervisorsampleform_test_type'),
    ]

    operations = [
    ]
