# Generated by Django 4.1 on 2023-07-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_supervisorsampleform_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='super_visor_sample_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_has_parameter_analyst', to='management.supervisorsampleform'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('Chemical', 'Chemical'), ('Instrumental', 'Instrumental'), ('Microbiological', 'Microbiological')], default=None, max_length=155, null=True),
        ),
    ]
