# Generated by Django 4.1 on 2023-07-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_merge_20230630_1208'),
        ('management', '0080_sampleformhasparameter_super_visor_sample_form_and_more'),
    ]

    operations = [
    ]
