# Generated by Django 4.1 on 2023-07-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_alter_sampleformhasparameter_super_visor_sample_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='commodity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sample_has_parameter_analyst', to='management.commodity'),
        ),
    ]
