# Generated by Django 4.1 on 2023-07-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_merge_20230701_1203'),
        ('management', '0082_alter_sampleformhasparameter_super_visor_sample_form'),
    ]

    operations = [
    ]
