# Generated by Django 4.1 on 2023-07-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0083_merge_20230701_1829'),
        ('management', '0085_alter_sampleformverifier_super_visor_sample_form'),
    ]

    operations = [
    ]
