# Generated by Django 4.1 on 2023-07-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_alter_sampleformverifier_super_visor_sample_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleformverifier',
            name='super_visor_sample_form',
        ),
    ]
