# Generated by Django 4.1 on 2023-07-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0086_merge_20230701_2016'),
        ('management', '0086_remove_sampleformverifier_super_visor_sample_form'),
    ]

    operations = [
    ]
