# Generated by Django 4.1 on 2023-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0086_remove_sampleformverifier_super_visor_sample_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected'), ('not_verified', 'not_verified'), ('tested', 'tested'), ('verified', 'verified')], default='pending', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('recheck', 'recheck'), ('completed', 'completed'), ('tested', 'tested'), ('processing', 'processing')], default='processing', max_length=155),
        ),
        migrations.AlterField(
            model_name='supervisorsampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('not_assigned', 'not_assigned'), ('processing', 'processing'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected'), ('not_verified', 'not_verified'), ('tested', 'tested'), ('verified', 'verified')], default='not_assigned', max_length=155, null=True),
        ),
    ]
