# Generated by Django 4.1 on 2023-07-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0087_alter_sampleformhasparameter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='test_type',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
