# Generated by Django 4.1 on 2023-07-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0087_alter_sampleformhasparameter_status_and_more'),
        ('management', '0087_merge_20230701_2121'),
    ]

    operations = [
    ]
