# Generated by Django 4.1 on 2023-07-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_merge_20230702_1823'),
        ('management', '0088_rawdatasheet_test_type'),
    ]

    operations = [
    ]
