# Generated by Django 4.1 on 2023-07-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_rawdatasheet_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='super_visor_sample_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_datasheet', to='management.supervisorsampleform'),
        ),
    ]
