# Generated by Django 4.1 on 2023-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0089_rawdatasheet_super_visor_sample_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformverifier',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('recheck', 'recheck'), ('not_approved', 'not_approved'), ('completed', 'completed')], default='processing', max_length=155),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('not_assigned', 'not_assigned'), ('not_verified', 'not_verified'), ('not_approved', 'not_approved'), ('verified', 'verified'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorsampleform',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('not_assigned', 'not_assigned'), ('processing', 'processing'), ('completed', 'completed'), ('recheck', 'recheck'), ('rejected', 'rejected'), ('not_verified', 'not_verified'), ('not_approved', 'not_approved'), ('tested', 'tested'), ('verified', 'verified')], default='not_assigned', max_length=155, null=True),
        ),
    ]
