# Generated by Django 4.1 on 2023-07-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0089_merge_20230703_0135'),
        ('management', '0089_rawdatasheet_super_visor_sample_form'),
    ]

    operations = [
    ]
