# Generated by Django 4.1 on 2023-07-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0090_sampleformverifier_status_alter_sampleform_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleform',
            old_name='analyst_encode_id',
            new_name='refrence_number',
        ),
        migrations.RenameField(
            model_name='sampleform',
            old_name='supervisor_encode_id',
            new_name='sample_lab_id',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='user_encode_id',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='verifier_encode_id',
        ),
    ]
