# Generated by Django 4.1 on 2023-07-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_alter_sampleformhasparameter_status'),
        ('management', '0091_rename_analyst_encode_id_sampleform_refrence_number_and_more'),
    ]

    operations = [
    ]
