# Generated by Django 4.1 on 2023-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0092_sampleformparameterformulacalculate_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
