# Generated by Django 4.1 on 2023-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0093_sampleform_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='sample_quantity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='sample_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='sample_units',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
