# Generated by Django 4.1 on 2023-07-11 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0094_sampleform_sample_quantity_sampleform_sample_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
