# Generated by Django 4.1 on 2023-07-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0092_merge_20230707_1226'),
        ('management', '0094_sampleform_sample_quantity_sampleform_sample_type_and_more'),
    ]

    operations = [
    ]
