# Generated by Django 4.1 on 2023-07-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_alter_payment_sample_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sample_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='management.sampleform'),
        ),
    ]
