# Generated by Django 4.1 on 2023-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0098_alter_payment_sample_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='days_dfb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='dfb_duration',
            field=models.CharField(choices=[('days', 'days'), ('month', 'month'), ('year', 'year')], default=None, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='dfb_type',
            field=models.CharField(choices=[('days', 'days'), ('date', 'date')], default=None, max_length=155, null=True),
        ),
    ]
