# Generated by Django 4.1 on 2023-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_sampleform_days_dfb_sampleform_dfb_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='dfb',
            field=models.DateField(null=True),
        ),
    ]
