# Generated by Django 4.1 on 2023-07-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0100_alter_sampleform_dfb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='dfb_duration',
            field=models.CharField(choices=[('days', 'days'), ('month', 'month'), ('year', 'year'), ('', '')], default=None, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='dfb_type',
            field=models.CharField(choices=[('days', 'days'), ('date', 'date'), ('', '')], default=None, max_length=155, null=True),
        ),
    ]
