# Generated by Django 4.1 on 2023-07-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0095_merge_20230710_1527'),
        ('management', '0102_alter_sampleform_days_dfb'),
    ]

    operations = [
    ]
