# Generated by Django 4.1 on 2023-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0103_microparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='microparameter',
            name='date_of_incubation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='diluent_used',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='media_used',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='negative_control_used',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='physical_condition_of_sample',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='positive_control_used',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='prepared_dilution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameter',
            name='required_temperature',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
