# Generated by Django 4.1 on 2023-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0104_microparameter_date_of_incubation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroObservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_number', models.IntegerField(null=True)),
                ('observation_time', models.CharField(max_length=500, null=True)),
                ('temperature', models.CharField(max_length=500, null=True)),
                ('time', models.CharField(max_length=500, null=True)),
                ('first_exponent', models.CharField(max_length=500, null=True)),
                ('first_exponent_a', models.CharField(max_length=500, null=True)),
                ('first_exponent_b', models.CharField(max_length=500, null=True)),
                ('second_exponent', models.CharField(max_length=500, null=True)),
                ('second_exponent_a', models.CharField(max_length=500, null=True)),
                ('second_exponent_b', models.CharField(max_length=500, null=True)),
                ('third_exponent', models.CharField(max_length=500, null=True)),
                ('third_exponent_a', models.CharField(max_length=500, null=True)),
                ('third_exponent_b', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
