# Generated by Django 4.1 on 2023-07-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0103_merge_20230711_1136'),
        ('management', '0105_microobservationtable'),
    ]

    operations = [
    ]
