# Generated by Django 4.1 on 2023-07-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0106_merge_20230711_1150'),
        ('management', '0106_microobservationtable_micro_parameter_table_and_more'),
    ]

    operations = [
    ]
