# Generated by Django 4.1 on 2023-07-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0107_alter_testresult_mandatory_standard_and_more'),
        ('management', '0107_merge_20230711_1732'),
    ]

    operations = [
    ]
