# Generated by Django 4.1 on 2023-07-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0110_sampleformparameterformulacalculate_analyst_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleformparameterformulacalculate',
            name='analyst_remarks',
        ),
    ]
