# Generated by Django 4.1 on 2023-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0111_remove_sampleformparameterformulacalculate_analyst_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformparameterformulacalculate',
            name='analyst_remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
