# Generated by Django 4.1 on 2023-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0113_microobservationtable_negative_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microobservationtable',
            name='observation_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
