# Generated by Django 4.1 on 2023-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0114_alter_microobservationtable_observation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microobservationtable',
            name='first_exponent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='first_exponent_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='first_exponent_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='negative_control',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='observation_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='observation_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='positive_control',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='second_exponent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='second_exponent_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='second_exponent_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='temperature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='third_exponent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='third_exponent_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='third_exponent_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microobservationtable',
            name='time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
