# Generated by Django 4.1 on 2023-07-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_sampleformparameterformulacalculate_converted_result_and_more'),
        ('management', '0115_alter_microobservationtable_first_exponent_and_more'),
    ]

    operations = [
    ]
