# Generated by Django 4.1 on 2023-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_merge_20230712_1213'),
        ('management', '0117_microparameter_status'),
    ]

    operations = [
    ]
