# Generated by Django 4.1 on 2023-07-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0118_merge_20230713_1203'),
        ('management', '0119_sampleform_admin_remarks_sampleform_verifier_remarks'),
    ]

    operations = [
    ]
