# Generated by Django 4.1 on 2023-07-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0120_alter_supervisorsampleform_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='analyst_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sample_has_parameter_analyst', to=settings.AUTH_USER_MODEL),
        ),
    ]
