# Generated by Django 4.1 on 2023-07-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_merge_20230716_1220'),
        ('management', '0121_alter_sampleformhasparameter_analyst_user'),
    ]

    operations = [
    ]
