# Generated by Django 4.1 on 2023-07-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_sampleformhasparameter_completed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleformhasparameter',
            old_name='sample_receive_date',
            new_name='sample_received_date',
        ),
    ]
