# Generated by Django 4.1 on 2023-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0123_rename_sample_receive_date_sampleformhasparameter_sample_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='sample_received_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheet',
            name='started_date',
            field=models.DateTimeField(null=True),
        ),
    ]
