# Generated by Django 4.1 on 2023-07-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0124_rawdatasheet_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_sub_category', models.CharField(choices=[('licensing', 'licensing'), ('survelliance', 'survelliance'), ('formal', 'formal'), ('gap', 'gap'), ('standard_formation', 'standard_formation'), ('import_export', 'import_export'), ('null', 'null')], default='null', max_length=155)),
                ('client_category', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image2', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image3', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image4', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image5', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image6', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image7', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image8', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image9', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('image10', models.FileField(null=True, upload_to='uploads/clientcategorydetail')),
                ('sample_form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientCategoryDetail', to='management.sampleform')),
            ],
        ),
    ]
