# Generated by Django 4.1 on 2023-07-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0126_remove_clientcategorydetail_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcategorydetail',
            name='sample_form',
        ),
        migrations.AddField(
            model_name='sampleform',
            name='client_category_detail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_form', to='management.clientcategorydetail'),
        ),
        migrations.AlterField(
            model_name='clientcategorydetail',
            name='client_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientCategoryDetail', to='management.clientcategory'),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='batch',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
