# Generated by Django 4.1 on 2023-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0127_remove_clientcategorydetail_sample_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcategorydetail',
            name='client_sub_category',
            field=models.CharField(choices=[('licensing', 'licensing'), ('surveillance', 'surveillance'), ('formal', 'formal'), ('gap', 'gap'), ('standard_formation', 'standard_formation'), ('import_export', 'import_export'), ('null', 'null')], default='null', max_length=155),
        ),
    ]
