# Generated by Django 4.1 on 2023-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0129_rename_image_clientcategorydetailimages_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategorydetailimages',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
