# Generated by Django 4.1 on 2023-07-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0130_clientcategorydetailimages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='number_of_sample',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clientcategorydetail',
            name='client_sub_category',
            field=models.CharField(choices=[('licensing', 'licensing'), ('surveillance', 'surveillance'), ('formal', 'formal'), ('gap', 'gap'), ('standard_formation', 'standard_formation'), ('import_export', 'import_export'), ('', '')], default='null', max_length=155),
        ),
    ]
