# Generated by Django 4.1 on 2023-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_merge_20230719_1202'),
        ('management', '0131_sampleform_number_of_sample_and_more'),
    ]

    operations = [
    ]
