# Generated by Django 4.1 on 2023-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0131_sampleform_number_of_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
