# Generated by Django 4.1 on 2023-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0132_sampleformhasparameter_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
