# Generated by Django 4.1 on 2023-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0133_rawdatasheet_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheetdetail',
            name='analyst_remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheetdetail',
            name='converted_result',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawdatasheetdetail',
            name='decimal_place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
