# Generated by Django 4.1 on 2023-07-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0134_rawdatasheetdetail_analyst_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microparameter',
            name='sample_form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='micro_detail', to='management.sampleform'),
        ),
    ]
