# Generated by Django 4.1 on 2023-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0135_alter_microparameter_sample_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_standard', models.CharField(max_length=500, null=True)),
                ('mandatory_standard_nepali', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_test_method', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=100, null=True)),
                ('units_nepali', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='mandatory_standard_nepali',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='ref_test_method',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='units_nepali',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='mandatory_standard',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='units',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_method',
            field=models.ManyToManyField(blank=True, related_name='test_result', to='management.testmethod'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='mandatory_standard',
            field=models.ManyToManyField(blank=True, related_name='test_result', to='management.mandatorystandard'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='test_result', to='management.units'),
        ),
    ]
