# Generated by Django 4.1 on 2023-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0139_microparameter_first_exponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microparameter',
            name='prepared_dilution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
