# Generated by Django 4.1 on 2023-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0141_alter_testresult_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='formula_notation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
