# Generated by Django 4.1 on 2023-08-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0132_merge_20230725_0846'),
        ('management', '0142_alter_testresult_formula_notation'),
    ]

    operations = [
    ]
