# Generated by Django 4.1 on 2023-08-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0142_alter_testresult_formula_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microparameterrawdata',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='microparameterrawdata',
            name='sample_form',
        ),
        migrations.RemoveField(
            model_name='microparameterrawdata',
            name='sample_form_has_parameter',
        ),
        migrations.DeleteModel(
            name='MicroObservationTableRawData',
        ),
        migrations.DeleteModel(
            name='MicroParameterRawData',
        ),
    ]
