# Generated by Django 4.1 on 2023-08-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0143_remove_microparameterrawdata_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='commodity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='management.commodity'),
        ),
    ]
