# Generated by Django 4.1 on 2023-08-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0144_alter_testresult_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroParameterRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_condition_of_sample', models.CharField(max_length=500, null=True)),
                ('media_used', models.CharField(max_length=500, null=True)),
                ('prepared_dilution', models.CharField(blank=True, max_length=500, null=True)),
                ('diluent_used', models.CharField(max_length=500, null=True)),
                ('positive_control_used', models.CharField(max_length=500, null=True)),
                ('negative_control_used', models.CharField(max_length=500, null=True)),
                ('date_of_incubation', models.DateTimeField(null=True)),
                ('required_temperature', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=2000, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('first_exponent', models.CharField(default=None, max_length=500)),
                ('second_exponent', models.CharField(default=None, max_length=500)),
                ('third_exponent', models.CharField(default=None, max_length=500)),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.testresult')),
                ('sample_form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='micro_detail_raw_data', to='management.sampleform')),
                ('sample_form_has_parameter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_detail_raw_data', to='management.sampleformhasparameter')),
            ],
        ),
        migrations.CreateModel(
            name='MicroObservationTableRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_number', models.CharField(blank=True, max_length=500, null=True)),
                ('observation_time', models.CharField(blank=True, max_length=500, null=True)),
                ('temperature', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
                ('first_exponent', models.CharField(blank=True, max_length=500, null=True)),
                ('first_exponent_a', models.CharField(blank=True, max_length=500, null=True)),
                ('first_exponent_b', models.CharField(blank=True, max_length=500, null=True)),
                ('second_exponent', models.CharField(blank=True, max_length=500, null=True)),
                ('second_exponent_a', models.CharField(blank=True, max_length=500, null=True)),
                ('second_exponent_b', models.CharField(blank=True, max_length=500, null=True)),
                ('third_exponent', models.CharField(blank=True, max_length=500, null=True)),
                ('third_exponent_a', models.CharField(blank=True, max_length=500, null=True)),
                ('third_exponent_b', models.CharField(blank=True, max_length=500, null=True)),
                ('negative_control', models.CharField(blank=True, max_length=500, null=True)),
                ('positive_control', models.CharField(blank=True, max_length=500, null=True)),
                ('micro_parameter_table_raw_data', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_observation_table_raw_data', to='management.microparameterrawdata')),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.testresult')),
                ('sample_form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_observation_table_raw_data', to='management.sampleform')),
            ],
        ),
        migrations.AlterField(
            model_name='rawdatasheetdetail',
            name='micro_table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='management.microparameterrawdata'),
        ),
    ]
