# Generated by Django 4.1 on 2023-08-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0145_microparameterrawdata_microobservationtablerawdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microobservationtablerawdata',
            name='micro_parameter_table_raw_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='micro_observation_table_raw_data', to='management.microparameterrawdata'),
        ),
    ]
