# Generated by Django 4.1 on 2023-08-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0147_remove_microparameterrawdata_sample_form_has_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='microparameterrawdata',
            name='sample_form_has_parameter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_detail_raw_data', to='management.sampleformhasparameter'),
        ),
    ]
