# Generated by Django 4.1 on 2023-08-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0148_microparameterrawdata_sample_form_has_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microparameterrawdata',
            name='sample_form_has_parameter',
        ),
    ]
