# Generated by Django 4.1 on 2023-08-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0150_microparameterrawdata_sample_form_has_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microobservationtablerawdata',
            name='micro_parameter_table_raw_data',
        ),
    ]
