# Generated by Django 4.1 on 2023-08-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0152_microobservationtablerawdata_micro_parameter_table_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdatasheetdetail',
            name='micro_table',
        ),
    ]
