# Generated by Django 4.1 on 2023-08-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0153_remove_rawdatasheetdetail_micro_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheetdetail',
            name='micro_table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='management.microparameterrawdata'),
        ),
    ]
