# Generated by Django 4.1 on 2023-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0155_sampleformparameterformulacalculate_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheetdetail',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
