# Generated by Django 4.1 on 2023-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0156_rawdatasheetdetail_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='analysis_fee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='sample_symbol_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='voucher_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='voucher_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
