# Generated by Django 4.1 on 2023-08-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0143_merge_20230807_0521'),
        ('management', '0156_rawdatasheetdetail_additional_info'),
    ]

    operations = [
    ]
