# Generated by Django 4.1 on 2023-08-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0157_merge_20230814_0451'),
        ('management', '0158_alter_microobservationtable_time_and_more'),
    ]

    operations = [
    ]
