# Generated by Django 4.1 on 2023-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0158_alter_microobservationtable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='dfb',
            field=models.DateField(blank=True, null=True),
        ),
    ]
