# Generated by Django 4.1 on 2023-08-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0159_alter_sampleform_dfb'),
        ('management', '0159_merge_20230816_0712'),
    ]

    operations = [
    ]
