# Generated by Django 4.1 on 2023-08-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0160_alter_sampleform_brand_alter_sampleform_condition_and_more'),
        ('management', '0160_merge_20230816_1148'),
    ]

    operations = [
    ]
