# Generated by Django 4.1 on 2023-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0160_alter_sampleform_brand_alter_sampleform_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='analysis_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
