# Generated by Django 4.1 on 2023-08-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0161_merge_20230817_0900'),
        ('management', '0161_sampleform_analysis_pricing'),
    ]

    operations = [
    ]
