# Generated by Django 4.1 on 2023-08-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0161_sampleform_analysis_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microparameter',
            name='first_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameter',
            name='second_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameter',
            name='third_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameterrawdata',
            name='first_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameterrawdata',
            name='second_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameterrawdata',
            name='third_exponent',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
