# Generated by Django 4.1 on 2023-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0162_alter_microparameter_first_exponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
