# Generated by Django 4.1 on 2023-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0163_fiscalyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='fiscal_year',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
