# Generated by Django 4.1 on 2023-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0164_sampleform_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='code',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='namuna_code',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
