# Generated by Django 4.1 on 2023-08-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0162_merge_20230817_1219'),
        ('management', '0165_sampleform_code_sampleform_namuna_code'),
    ]

    operations = [
    ]
