# Generated by Django 4.1 on 2023-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0165_sampleform_code_sampleform_namuna_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='dfb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='mfd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='voucher_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
