# Generated by Django 4.1 on 2023-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0166_alter_sampleform_dfb_alter_sampleform_mfd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasheet',
            name='sample_received_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatasheet',
            name='started_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='sample_received_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='started_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
