# Generated by Django 4.1 on 2023-09-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0166_merge_20230828_1000'),
        ('management', '0167_alter_rawdatasheet_sample_received_date_and_more'),
    ]

    operations = [
    ]
