# Generated by Django 4.1 on 2023-09-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0168_alter_sampleform_dfb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microparameter',
            name='duration_of_incubation',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='microparameterrawdata',
            name='duration_of_incubation',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
