# Generated by Django 4.1 on 2023-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0169_microparameter_duration_of_incubation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleformhasparameter',
            name='sample_receipt_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
