# Generated by Django 4.1 on 2023-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0168_alter_sampleform_dfb_and_more'),
        ('management', '0169_alter_supervisorsampleform_status'),
    ]

    operations = [
    ]
