# Generated by Django 4.1 on 2023-09-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0169_microparameter_duration_of_incubation_and_more'),
        ('management', '0170_merge_20230910_1050'),
    ]

    operations = [
    ]
