# Generated by Django 4.1 on 2023-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0170_sampleformhasparameter_sample_receipt_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasheet',
            name='sample_receipt_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
