# Generated by Django 4.1 on 2023-09-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0171_merge_20230912_0941'),
        ('management', '0171_rawdatasheet_sample_receipt_condition'),
    ]

    operations = [
    ]
