# Generated by Django 4.1 on 2023-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0171_rawdatasheet_sample_receipt_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='microparameter',
            name='time_of_incubation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='microparameterrawdata',
            name='time_of_incubation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameter',
            name='date_of_incubation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameter',
            name='diluent_used',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='microparameterrawdata',
            name='diluent_used',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
