# Generated by Django 4.1 on 2023-10-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0172_merge_20230919_1001'),
        ('management', '0174_alter_microobservationtable_time_and_more'),
    ]

    operations = [
    ]
