# Generated by Django 4.1 on 2023-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0175_merge_20231006_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasheet',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatasheetdetail',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformverifier',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sampleformverifier',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
