# Generated by Django 4.1 on 2023-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0177_alter_payment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasheet',
            name='additional_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatasheetdetail',
            name='additional_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatasheetdetail',
            name='analyst_remarks',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformhasparameter',
            name='additional_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='additional_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sampleformparameterformulacalculate',
            name='analyst_remarks',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
