# Generated by Django 4.1 on 2023-11-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0178_alter_rawdatasheet_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleform',
            name='created_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_form_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleform',
            name='owner_user_obj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user_have_sample_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
