# Generated by Django 4.1 on 2023-12-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0183_verifiedlist_approvedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verifiedlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
