over_all_status = {
    'not_verified':"not verified",
    'not_approved':"not approved",
    'verified':"verified",
    'not_assigned':"not assigned",
    're-assign':"re-assign",
    'recheck':"recheck",
    'pending':"pending",
    'processing':"processing",
    'completed':"completed",
    'rejected' : 'rejected',
    'reject'  : 'rejected',
    'tested' : 'Test Completed',
    'Test Completed' : 'Test Completed',
}