# Generated by Django 4.1 on 2023-05-22 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_name', models.CharField(max_length=200, null=True)),
                ('from_notification', models.EmailField(max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('group_notification', models.CharField(blank=True, choices=[('SUPERADMIN', 'SUPERADMIN'), ('SMU', 'SMU'), ('SUPERVISOR', 'SUPERVISOR'), ('ANALYST', 'ANALYST'), ('USER', 'USER')], max_length=1000, null=True)),
                ('to_notification', models.ManyToManyField(related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
