# Generated by Django 4.1 on 2023-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_name',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_notification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
