# Generated by Django 4.1 on 2023-06-20 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_rename_notification_name_notification_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
