# Generated by Django 4.1 on 2023-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0004_notification_isinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='particular_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='group_notification',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'SUPERADMIN'), ('SMU', 'SMU'), ('SUPERVISOR', 'SUPERVISOR'), ('ANALYST', 'ANALYST'), ('USER', 'USER'), ('USER_ADMIN', 'USER_ADMIN')], max_length=1000, null=True),
        ),
    ]
