# Generated by Django 4.1 on 2023-08-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0006_alter_notification_group_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isinstance_id',
            new_name='instance_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
