
main_url = "https://lims-home.netlify.app/"

add_sample_form = "/dashboard/add-sample"
user_request = "/dashboard/user-requests"
sample_request = "/dashboard/sample-requests"
all_users = "/dashboard/all-users"
client_category = "/dashboard/settings/client-category"
commodity= "/dashboard/commodities/all-commodities"
commodity_category = "/dashboard/settings/commodity-category"
parameter = "/dashboard/commodities-parameter"
my_account = "/dashboard/my-account"
particular_user = "/dashboard/user-details/"
user_my_sample = "/dashboard/sample-details/"

smu_sample_request_details ="/dashboard/sample-request-details/"
supervisor_sample_request_details ="/dashboard/lab-sample-details/"
analyst_sample_request_details = "/dashboard/test-request-details/" 
verifier_sample_request_details = "/dashboard/verify-sample-report/" 
admin_sample_request_details = "/dashboard/admin-sample-request-details/"
